#include <bearshares/protocol/get_config.hpp>
#include <bearshares/protocol/config.hpp>
#include <bearshares/protocol/asset.hpp>
#include <bearshares/protocol/types.hpp>
#include <bearshares/protocol/version.hpp>

namespace bearshares { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["BSD_SYMBOL"] = BSD_SYMBOL;
   result["BEARSHARES_100_PERCENT"] = BEARSHARES_100_PERCENT;
   result["BEARSHARES_1_PERCENT"] = BEARSHARES_1_PERCENT;
   result["BEARSHARES_1_TENTH_PERCENT"] = BEARSHARES_1_TENTH_PERCENT;
   result["BEARSHARES_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = BEARSHARES_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["BEARSHARES_ACTIVE_CHALLENGE_COOLDOWN"] = BEARSHARES_ACTIVE_CHALLENGE_COOLDOWN;
   result["BEARSHARES_ACTIVE_CHALLENGE_FEE"] = BEARSHARES_ACTIVE_CHALLENGE_FEE;
   result["BEARSHARES_ADDRESS_PREFIX"] = BEARSHARES_ADDRESS_PREFIX;
   result["BEARSHARES_APR_PERCENT_MULTIPLY_PER_BLOCK"] = BEARSHARES_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["BEARSHARES_APR_PERCENT_MULTIPLY_PER_HOUR"] = BEARSHARES_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["BEARSHARES_APR_PERCENT_MULTIPLY_PER_ROUND"] = BEARSHARES_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["BEARSHARES_APR_PERCENT_SHIFT_PER_BLOCK"] = BEARSHARES_APR_PERCENT_SHIFT_PER_BLOCK;
   result["BEARSHARES_APR_PERCENT_SHIFT_PER_HOUR"] = BEARSHARES_APR_PERCENT_SHIFT_PER_HOUR;
   result["BEARSHARES_APR_PERCENT_SHIFT_PER_ROUND"] = BEARSHARES_APR_PERCENT_SHIFT_PER_ROUND;
   result["BEARSHARES_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = BEARSHARES_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["BEARSHARES_BANDWIDTH_PRECISION"] = BEARSHARES_BANDWIDTH_PRECISION;
   result["BEARSHARES_BLOCKCHAIN_PRECISION"] = BEARSHARES_BLOCKCHAIN_PRECISION;
   result["BEARSHARES_BLOCKCHAIN_PRECISION_DIGITS"] = BEARSHARES_BLOCKCHAIN_PRECISION_DIGITS;
   result["BEARSHARES_BLOCKCHAIN_HARDFORK_VERSION"] = BEARSHARES_BLOCKCHAIN_HARDFORK_VERSION;
   result["BEARSHARES_BLOCKCHAIN_VERSION"] = BEARSHARES_BLOCKCHAIN_VERSION;
   result["BEARSHARES_BLOCK_INTERVAL"] = BEARSHARES_BLOCK_INTERVAL;
   result["BEARSHARES_BLOCKS_PER_DAY"] = BEARSHARES_BLOCKS_PER_DAY;
   result["BEARSHARES_BLOCKS_PER_HOUR"] = BEARSHARES_BLOCKS_PER_HOUR;
   result["BEARSHARES_BLOCKS_PER_YEAR"] = BEARSHARES_BLOCKS_PER_YEAR;
   result["BEARSHARES_CASHOUT_WINDOW_SECONDS"] = BEARSHARES_CASHOUT_WINDOW_SECONDS;
   result["BEARSHARES_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = BEARSHARES_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["BEARSHARES_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = BEARSHARES_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["BEARSHARES_CHAIN_ID"] = BEARSHARES_CHAIN_ID;
   result["BEARSHARES_COMMENT_REWARD_FUND_NAME"] = BEARSHARES_COMMENT_REWARD_FUND_NAME;
   result["BEARSHARES_CONTENT_APR_PERCENT"] = BEARSHARES_CONTENT_APR_PERCENT;
   result["BEARSHARES_CONTENT_CONSTANT_HF0"] = BEARSHARES_CONTENT_CONSTANT_HF0;
   result["BEARSHARES_CONTENT_REWARD_PERCENT"] = BEARSHARES_CONTENT_REWARD_PERCENT;
   result["BEARSHARES_CONVERSION_DELAY"] = BEARSHARES_CONVERSION_DELAY;
   result["BEARSHARES_CONVERSION_DELAY_PRE_HF_16"] = BEARSHARES_CONVERSION_DELAY_PRE_HF_16;
   result["BEARSHARES_CREATE_ACCOUNT_DELEGATION_RATIO"] = BEARSHARES_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["BEARSHARES_CREATE_ACCOUNT_DELEGATION_TIME"] = BEARSHARES_CREATE_ACCOUNT_DELEGATION_TIME;
   result["BEARSHARES_CREATE_ACCOUNT_WITH_BEARS_MODIFIER"] = BEARSHARES_CREATE_ACCOUNT_WITH_BEARS_MODIFIER;
   result["BEARSHARES_CURATE_APR_PERCENT"] = BEARSHARES_CURATE_APR_PERCENT;
   result["BEARSHARES_DEFAULT_BSD_INTEREST_RATE"] = BEARSHARES_DEFAULT_BSD_INTEREST_RATE;
   result["BEARSHARES_EQUIHASH_K"] = BEARSHARES_EQUIHASH_K;
   result["BEARSHARES_EQUIHASH_N"] = BEARSHARES_EQUIHASH_N;
   result["BEARSHARES_FEED_HISTORY_WINDOW"] = BEARSHARES_FEED_HISTORY_WINDOW;
   result["BEARSHARES_FEED_HISTORY_WINDOW_PRE_HF_16"] = BEARSHARES_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["BEARSHARES_FEED_INTERVAL_BLOCKS"] = BEARSHARES_FEED_INTERVAL_BLOCKS;
   result["BEARSHARES_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT"] = BEARSHARES_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT;
   result["BEARSHARES_GENESIS_TIME"] = BEARSHARES_GENESIS_TIME;
   result["BEARSHARES_HARDFORK_REQUIRED_WITNESSES"] = BEARSHARES_HARDFORK_REQUIRED_WITNESSES;
   result["BEARSHARES_INFLATION_NARROWING_PERIOD"] = BEARSHARES_INFLATION_NARROWING_PERIOD;
   result["BEARSHARES_INFLATION_RATE_START_PERCENT"] = BEARSHARES_INFLATION_RATE_START_PERCENT;
   result["BEARSHARES_INFLATION_RATE_STOP_PERCENT"] = BEARSHARES_INFLATION_RATE_STOP_PERCENT;
   result["BEARSHARES_INIT_MINER_NAME"] = BEARSHARES_INIT_MINER_NAME;
   result["BEARSHARES_INIT_PUBLIC_KEY_STR"] = BEARSHARES_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["BEARSHARES_INIT_PRIVATE_KEY"] = BEARSHARES_INIT_PRIVATE_KEY;
#endif
   result["BEARSHARES_INIT_SUPPLY"] = BEARSHARES_INIT_SUPPLY;
   result["BEARSHARES_INIT_TIME"] = BEARSHARES_INIT_TIME;
   result["BEARSHARES_IRREVERSIBLE_THRESHOLD"] = BEARSHARES_IRREVERSIBLE_THRESHOLD;
   result["BEARSHARES_LIQUIDITY_APR_PERCENT"] = BEARSHARES_LIQUIDITY_APR_PERCENT;
   result["BEARSHARES_LIQUIDITY_REWARD_BLOCKS"] = BEARSHARES_LIQUIDITY_REWARD_BLOCKS;
   result["BEARSHARES_LIQUIDITY_REWARD_PERIOD_SEC"] = BEARSHARES_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BEARSHARES_LIQUIDITY_TIMEOUT_SEC"] = BEARSHARES_LIQUIDITY_TIMEOUT_SEC;
   result["BEARSHARES_MAX_ACCOUNT_NAME_LENGTH"] = BEARSHARES_MAX_ACCOUNT_NAME_LENGTH;
   result["BEARSHARES_MAX_ACCOUNT_WITNESS_VOTES"] = BEARSHARES_MAX_ACCOUNT_WITNESS_VOTES;
   result["BEARSHARES_MAX_ASSET_WHITELIST_AUTHORITIES"] = BEARSHARES_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["BEARSHARES_MAX_AUTHORITY_MEMBERSHIP"] = BEARSHARES_MAX_AUTHORITY_MEMBERSHIP;
   result["BEARSHARES_MAX_BLOCK_SIZE"] = BEARSHARES_MAX_BLOCK_SIZE;
   result["BEARSHARES_MAX_CASHOUT_WINDOW_SECONDS"] = BEARSHARES_MAX_CASHOUT_WINDOW_SECONDS;
   result["BEARSHARES_MAX_COMMENT_DEPTH"] = BEARSHARES_MAX_COMMENT_DEPTH;
   result["BEARSHARES_MAX_COMMENT_DEPTH_PRE_HF17"] = BEARSHARES_MAX_COMMENT_DEPTH_PRE_HF17;
   result["BEARSHARES_MAX_FEED_AGE_SECONDS"] = BEARSHARES_MAX_FEED_AGE_SECONDS;
   result["BEARSHARES_MAX_INSTANCE_ID"] = BEARSHARES_MAX_INSTANCE_ID;
   result["BEARSHARES_MAX_MEMO_SIZE"] = BEARSHARES_MAX_MEMO_SIZE;
   result["BEARSHARES_MAX_WITNESSES"] = BEARSHARES_MAX_WITNESSES;
   result["BEARSHARES_MAX_MINER_WITNESSES_HF0"] = BEARSHARES_MAX_MINER_WITNESSES_HF0;
   result["BEARSHARES_MAX_MINER_WITNESSES_HF17"] = BEARSHARES_MAX_MINER_WITNESSES_HF17;
   result["BEARSHARES_MAX_PERMLINK_LENGTH"] = BEARSHARES_MAX_PERMLINK_LENGTH;
   result["BEARSHARES_MAX_PROXY_RECURSION_DEPTH"] = BEARSHARES_MAX_PROXY_RECURSION_DEPTH;
   result["BEARSHARES_MAX_RATION_DECAY_RATE"] = BEARSHARES_MAX_RATION_DECAY_RATE;
   result["BEARSHARES_MAX_RESERVE_RATIO"] = BEARSHARES_MAX_RESERVE_RATIO;
   result["BEARSHARES_MAX_RUNNER_WITNESSES_HF0"] = BEARSHARES_MAX_RUNNER_WITNESSES_HF0;
   result["BEARSHARES_MAX_RUNNER_WITNESSES_HF17"] = BEARSHARES_MAX_RUNNER_WITNESSES_HF17;
   result["BEARSHARES_MAX_SHARE_SUPPLY"] = BEARSHARES_MAX_SHARE_SUPPLY;
   result["BEARSHARES_MAX_SIG_CHECK_DEPTH"] = BEARSHARES_MAX_SIG_CHECK_DEPTH;
   result["BEARSHARES_MAX_TIME_UNTIL_EXPIRATION"] = BEARSHARES_MAX_TIME_UNTIL_EXPIRATION;
   result["BEARSHARES_MAX_TRANSACTION_SIZE"] = BEARSHARES_MAX_TRANSACTION_SIZE;
   result["BEARSHARES_MAX_UNDO_HISTORY"] = BEARSHARES_MAX_UNDO_HISTORY;
   result["BEARSHARES_MAX_URL_LENGTH"] = BEARSHARES_MAX_URL_LENGTH;
   result["BEARSHARES_MAX_VOTE_CHANGES"] = BEARSHARES_MAX_VOTE_CHANGES;
   result["BEARSHARES_MAX_VOTED_WITNESSES_HF0"] = BEARSHARES_MAX_VOTED_WITNESSES_HF0;
   result["BEARSHARES_MAX_VOTED_WITNESSES_HF17"] = BEARSHARES_MAX_VOTED_WITNESSES_HF17;
   result["BEARSHARES_MAX_WITHDRAW_ROUTES"] = BEARSHARES_MAX_WITHDRAW_ROUTES;
   result["BEARSHARES_MAX_WITNESS_URL_LENGTH"] = BEARSHARES_MAX_WITNESS_URL_LENGTH;
   result["BEARSHARES_MIN_ACCOUNT_CREATION_FEE"] = BEARSHARES_MIN_ACCOUNT_CREATION_FEE;
   result["BEARSHARES_MIN_ACCOUNT_NAME_LENGTH"] = BEARSHARES_MIN_ACCOUNT_NAME_LENGTH;
   result["BEARSHARES_MIN_BLOCK_SIZE"] = BEARSHARES_MIN_BLOCK_SIZE;
   result["BEARSHARES_MIN_BLOCK_SIZE_LIMIT"] = BEARSHARES_MIN_BLOCK_SIZE_LIMIT;
   result["BEARSHARES_MIN_CONTENT_REWARD"] = BEARSHARES_MIN_CONTENT_REWARD;
   result["BEARSHARES_MIN_CURATE_REWARD"] = BEARSHARES_MIN_CURATE_REWARD;
   result["BEARSHARES_MIN_PERMLINK_LENGTH"] = BEARSHARES_MIN_PERMLINK_LENGTH;
   result["BEARSHARES_MIN_REPLY_INTERVAL"] = BEARSHARES_MIN_REPLY_INTERVAL;
   result["BEARSHARES_MIN_ROOT_COMMENT_INTERVAL"] = BEARSHARES_MIN_ROOT_COMMENT_INTERVAL;
   result["BEARSHARES_MIN_VOTE_INTERVAL_SEC"] = BEARSHARES_MIN_VOTE_INTERVAL_SEC;
   result["BEARSHARES_MINER_ACCOUNT"] = BEARSHARES_MINER_ACCOUNT;
   result["BEARSHARES_MINER_PAY_PERCENT"] = BEARSHARES_MINER_PAY_PERCENT;
   result["BEARSHARES_MIN_FEEDS"] = BEARSHARES_MIN_FEEDS;
   result["BEARSHARES_MINING_REWARD"] = BEARSHARES_MINING_REWARD;
   result["BEARSHARES_MINING_TIME"] = BEARSHARES_MINING_TIME;
   result["BEARSHARES_MIN_LIQUIDITY_REWARD"] = BEARSHARES_MIN_LIQUIDITY_REWARD;
   result["BEARSHARES_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = BEARSHARES_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BEARSHARES_MIN_PAYOUT_BSD"] = BEARSHARES_MIN_PAYOUT_BSD;
   result["BEARSHARES_MIN_POW_REWARD"] = BEARSHARES_MIN_POW_REWARD;
   result["BEARSHARES_MIN_PRODUCER_REWARD"] = BEARSHARES_MIN_PRODUCER_REWARD;
   result["BEARSHARES_MIN_RATION"] = BEARSHARES_MIN_RATION;
   result["BEARSHARES_MIN_TRANSACTION_EXPIRATION_LIMIT"] = BEARSHARES_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["BEARSHARES_MIN_TRANSACTION_SIZE_LIMIT"] = BEARSHARES_MIN_TRANSACTION_SIZE_LIMIT;
   result["BEARSHARES_MIN_UNDO_HISTORY"] = BEARSHARES_MIN_UNDO_HISTORY;
   result["BEARSHARES_NULL_ACCOUNT"] = BEARSHARES_NULL_ACCOUNT;
   result["BEARSHARES_NUM_INIT_MINERS"] = BEARSHARES_NUM_INIT_MINERS;
   result["BEARSHARES_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = BEARSHARES_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["BEARSHARES_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = BEARSHARES_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["BEARSHARES_OWNER_AUTH_RECOVERY_PERIOD"] = BEARSHARES_OWNER_AUTH_RECOVERY_PERIOD;
   result["BEARSHARES_OWNER_CHALLENGE_COOLDOWN"] = BEARSHARES_OWNER_CHALLENGE_COOLDOWN;
   result["BEARSHARES_OWNER_CHALLENGE_FEE"] = BEARSHARES_OWNER_CHALLENGE_FEE;
   result["BEARSHARES_OWNER_UPDATE_LIMIT"] = BEARSHARES_OWNER_UPDATE_LIMIT;
   result["BEARSHARES_POST_AVERAGE_WINDOW"] = BEARSHARES_POST_AVERAGE_WINDOW;
   result["BEARSHARES_POST_MAX_BANDWIDTH"] = BEARSHARES_POST_MAX_BANDWIDTH;
   result["BEARSHARES_POST_REWARD_FUND_NAME"] = BEARSHARES_POST_REWARD_FUND_NAME;
   result["BEARSHARES_POST_WEIGHT_CONSTANT"] = BEARSHARES_POST_WEIGHT_CONSTANT;
   result["BEARSHARES_POW_APR_PERCENT"] = BEARSHARES_POW_APR_PERCENT;
   result["BEARSHARES_PRODUCER_APR_PERCENT"] = BEARSHARES_PRODUCER_APR_PERCENT;
   result["BEARSHARES_PROXY_TO_SELF_ACCOUNT"] = BEARSHARES_PROXY_TO_SELF_ACCOUNT;
   result["BEARSHARES_BSD_INTEREST_COMPOUND_INTERVAL_SEC"] = BEARSHARES_BSD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["BEARSHARES_SECONDS_PER_YEAR"] = BEARSHARES_SECONDS_PER_YEAR;
   result["BEARSHARES_RECENT_RSHARES_DECAY_RATE_HF19"] = BEARSHARES_RECENT_RSHARES_DECAY_RATE_HF19;
   result["BEARSHARES_RECENT_RSHARES_DECAY_RATE_HF17"] = BEARSHARES_RECENT_RSHARES_DECAY_RATE_HF17;
   result["BEARSHARES_REVERSE_AUCTION_WINDOW_SECONDS"] = BEARSHARES_REVERSE_AUCTION_WINDOW_SECONDS;
   result["BEARSHARES_ROOT_POST_PARENT"] = BEARSHARES_ROOT_POST_PARENT;
   result["BEARSHARES_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = BEARSHARES_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["BEARSHARES_SAVINGS_WITHDRAW_TIME"] = BEARSHARES_SAVINGS_WITHDRAW_TIME;
   result["BEARSHARES_BSD_START_PERCENT"] = BEARSHARES_BSD_START_PERCENT;
   result["BEARSHARES_BSD_STOP_PERCENT"] = BEARSHARES_BSD_STOP_PERCENT;
   result["BEARSHARES_SECOND_CASHOUT_WINDOW"] = BEARSHARES_SECOND_CASHOUT_WINDOW;
   result["BEARSHARES_SOFT_MAX_COMMENT_DEPTH"] = BEARSHARES_SOFT_MAX_COMMENT_DEPTH;
   result["BEARSHARES_START_MINER_VOTING_BLOCK"] = BEARSHARES_START_MINER_VOTING_BLOCK;
   result["BEARSHARES_START_COINING_BLOCK"] = BEARSHARES_START_COINING_BLOCK;
   result["BEARSHARES_SYMBOL"] = BEARSHARES_SYMBOL;
   result["BEARSHARES_TEMP_ACCOUNT"] = BEARSHARES_TEMP_ACCOUNT;
   result["BEARSHARES_UPVOTE_LOCKOUT_HF7"] = BEARSHARES_UPVOTE_LOCKOUT_HF7;
   result["BEARSHARES_UPVOTE_LOCKOUT_HF17"] = BEARSHARES_UPVOTE_LOCKOUT_HF17;
   result["BEARSHARES_COINING_FUND_PERCENT"] = BEARSHARES_COINING_FUND_PERCENT;
   result["BEARSHARES_COINING_WITHDRAW_INTERVALS"] = BEARSHARES_COINING_WITHDRAW_INTERVALS;
   result["BEARSHARES_COINING_WITHDRAW_INTERVALS_PRE_HF_16"] = BEARSHARES_COINING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["BEARSHARES_COINING_WITHDRAW_INTERVAL_SECONDS"] = BEARSHARES_COINING_WITHDRAW_INTERVAL_SECONDS;
   result["BEARSHARES_VOTE_CHANGE_LOCKOUT_PERIOD"] = BEARSHARES_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["BEARSHARES_VOTE_DUST_THRESHOLD"] = BEARSHARES_VOTE_DUST_THRESHOLD;
   result["BEARSHARES_VOTE_REGENERATION_SECONDS"] = BEARSHARES_VOTE_REGENERATION_SECONDS;
   result["BEARS_SYMBOL"] = BEARS_SYMBOL;
   result["SHRD_SYMBOL"] = SHRD_SYMBOL;
   result["COINS_SYMBOL"] = COINS_SYMBOL;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;

   return result;
}

} } // bearshares::protocol
